# Generated by Django 5.2.5 on 2025-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='force_popup',
            field=models.BooleanField(default=False),
        ),
    ]
