# Generated by Django 5.2.4 on 2025-07-27 13:27

import core.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='ktp',
            field=models.ImageField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='driver',
            name='nik',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
    ]
