# Generated by Django 5.2.4 on 2025-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_is_verified_driver_ktp_driver_nik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nik',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
