# Generated by Django 5.2.4 on 2025-09-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_nik_alter_driver_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='ktp',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nik',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
