# Generated by Django 5.2.4 on 2025-07-07 01:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_bookingrequest_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
