# Generated by Django 5.2.4 on 2025-07-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_trip_destination_point'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
